#!/bin/bash

# I took this from stack overflow. :shrug:
require_clean_work_tree () {
    # Update the index
    git update-index -q --ignore-submodules --refresh
    err=0

    # Disallow unstaged changes in the working tree
    if ! git diff-files --quiet --ignore-submodules --
    then
        echo >&2 "Can't deploy: you have unstaged changes."
        git diff-files --name-status -r --ignore-submodules -- >&2
        err=1
    fi

    # Disallow uncommitted changes in the index
    if ! git diff-index --cached --quiet HEAD --ignore-submodules --
    then
        echo >&2 "Can't deploy: your index contains uncommitted changes."
        git diff-index --cached --name-status -r --ignore-submodules HEAD -- >&2
        err=1
    fi

    if [ $err = 1 ]
    then
        echo >&2 "Please commit or stash them."
        exit 1
    fi
}

require_clean_work_tree

S3_INSTALLED="$(gem list s3_website | grep s3_website)"

if [ -z "$S3_INSTALLED" ]
    then
        echo "Error: The 's3_website' gem is not installed. The script will now exit."
fi

if ! git diff-index --cached --quiet HEAD --ignore-submodules --
    then
        echo >&2 "cannot $1: your index contains uncommitted changes."
        git diff-index --cached --name-status -r --ignore-submodules HEAD -- >&2
        err=1
fi

echo "********************************************"
echo "* Deploying codechangers.com to Amazon S3. *"
echo "********************************************"
s3_website push

echo "***************************************"
echo "* Pushing to github to sync versions. *"
echo "***************************************"
git add .
git commit -a -m "who needs commit messages :boom:"
git push origin master
